#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="${ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
ANDROID_API_LEVEL="${ANDROID_API_LEVEL:-35}"
ANDROID_BUILD_TOOLS="${ANDROID_BUILD_TOOLS:-35.0.0}"
ANDROID_NDK_VERSION="${ANDROID_NDK_VERSION:-27.2.12479018}"
ANDROID_CMAKE_VERSION="${ANDROID_CMAKE_VERSION:-3.22.1}"

ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-$ROOT_DIR/.android-sdk}"
ANDROID_HOME="${ANDROID_HOME:-$ANDROID_SDK_ROOT}"

JAVA_HOME_RESOLVED="${JAVA_HOME:-}"
if [[ -z "$JAVA_HOME_RESOLVED" ]] && command -v java >/dev/null 2>&1; then
  java_bin="$(command -v java)"
  java_bin_real="$(readlink -f "$java_bin" 2>/dev/null || echo "$java_bin")"
  JAVA_HOME_RESOLVED="$(cd "$(dirname "$java_bin_real")/.." && pwd)"
fi

NDK_ROOT="$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION"
CMAKE_ROOT="$ANDROID_SDK_ROOT/cmake/$ANDROID_CMAKE_VERSION"
BUILD_TOOLS_DIR="$ANDROID_SDK_ROOT/build-tools/$ANDROID_BUILD_TOOLS"
PLATFORM_DIR="$ANDROID_SDK_ROOT/platforms/android-$ANDROID_API_LEVEL"
SDKMANAGER_BIN="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"

cat <<EOT
ROOT_DIR=$ROOT_DIR
JAVA_HOME=$JAVA_HOME_RESOLVED
ANDROID_HOME=$ANDROID_HOME
ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
ANDROID_API_LEVEL=$ANDROID_API_LEVEL
ANDROID_BUILD_TOOLS=$ANDROID_BUILD_TOOLS
ANDROID_NDK_VERSION=$ANDROID_NDK_VERSION
ANDROID_CMAKE_VERSION=$ANDROID_CMAKE_VERSION
ANDROID_NDK_ROOT=$NDK_ROOT
ANDROID_CMAKE_ROOT=$CMAKE_ROOT
ANDROID_BUILD_TOOLS_DIR=$BUILD_TOOLS_DIR
ANDROID_PLATFORM_DIR=$PLATFORM_DIR
ANDROID_SDKMANAGER_BIN=$SDKMANAGER_BIN
EOT
